spring:
  web:
    resources:
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /**/*.js,/**/*.css,/js/**,/css/**,/icon/**
      cache:
        cachecontrol:
          max-age: 365d
  data:
    mongodb:
      uri: mongodb://localhost/leaf
logging:
  level:
    root: info